name:
  build-openwrt

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup build environ
        run: apt update && build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: clone openwrt
        run: git clone --depth 1 https://github.com/openwrt/openwrt.git

      - name: update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: make defconfig
        run: cd openwrt && make defconfig

      - name: build openwrt
        run: make -j$(proc)
