name:
  build-openwrt

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup build environ
        run: sudo apt update && sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: clone openwrt
        run: git clone --depth 1 https://github.com/openwrt/openwrt.git

      - name: update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: make defconfig
        run: cd openwrt && make ARCH=x86_64 defconfig

      - name: build openwrt
        run: cd openwrt && make -j$(nproc)

      - name: pick files
        if: steps.build.output.status == 'success' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "::set-env name=FIRMWARE::$(pwd)"
          echo "::set-output name=status::success"

      - name: upload
        uses: actions/upload-artifact@v4
        if: steps.pick.output.status == 'success' && !cancelled()
        with:
          name: OpenWrt_firmware
          path: ${{ env.FIRMWARE }}
